server:
  port: 8090
  servlet:
    context-path: /blog  //첫페이지 컨텍스트
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:

  //템플릿엔진을 jsp로 사용하는 경우 추가
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

    //DB설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

    //jpa 설정
  jpa:
    open-in-view: true
    //영속성을 프리젠테이션 계층까지 가져감. lazy loading가능
  hibernate:
    ddl-auto: create
    naming:
    //엔티티 만들 때 변수명과 DB필드명 설정하기
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    use-new-id-generator-mappings: false
  show-sql: true
  properties:
    hibernate.format_sql: true